[theme]
base = "dark"
primaryColor = "#2563EB"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#0F1B33"
textColor = "#E5E9F0"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
